site_name: Brainy
nav:
  - Welcome: index.md
  - Sidebar: sidebar.md
  - Home: home.md
  - Editor: editor.md
  - Search: search.md
  - Reviewer: reviewer.md
  - Sync: sync.md
  - Settings: settings.md
  - Backup: backup.md
theme: readthedocs
